name: Go Test

on:
  push:   # Triggers on push to any branch
  pull_request:   # Triggers on pull request to any branch

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'  # Set this to the version of Go you are using

      # Step 3: Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Install dependencies (go mod tidy ensures modules are correct)
      - name: Install dependencies
        run: go mod tidy

      # Step 5: Run Go tests
      - name: Run tests
        run: go test -v ./...

      # Optional Step 6: Check for Go formatting (best practice)
      - name: Check Go formatting
        run: go fmt ./...
